# Generated by Django 2.2.13 on 2020-06-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='タイトル')),
                ('slug', models.SlugField(verbose_name='スラッグ')),
                ('text', models.TextField(blank=True, verbose_name='本文')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_datetime', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
    ]
