# Generated by Django 2.2.13 on 2020-06-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0002_memo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memo',
            options={'ordering': ('-created_datetime',)},
        ),
        migrations.AlterField(
            model_name='memo',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='スラッグ'),
        ),
    ]
